### PR TITLE
added resources to list

### PR DESCRIPTION
**Pull request by achingachris**

### CODE REVIEW

**Comment by orama254** [comment]
Looks Good ✅

**Comment by achingachris** [comment]
Thank you, do you mind if I update the whole layout of the readme file

**Comment by orama254** [comment]
@achingachris Do you have a preview in mind that we can see (a screenshot, concept e.t.c).

**Comment by achingachris** [comment]
> @achingachris Do you have a preview in mind that we can see (a screenshot, concept e.t.c).


Have a look at this

https://github.com/bradtraversy/design-resources-for-developers

**Comment by orama254** [comment]
> > @achingachris Do you have a preview in mind that we can see (a screenshot, concept e.t.c).
> 
> Have a look at this
> 
> https://github.com/bradtraversy/design-resources-for-developers

it looks good...you can send over a pr and we can look at it

**Pull request merged**
