### PR TITLE
Updated Readme Layout and Added Content

### PR DESCRIPTION
**Pull request by achingachris**
- added resources to list
- new_layout_init
- added reactjs cheatsheets and layout

### CODE REVIEW

**Comment by orama254** [comment]
Hi @achingachris 

thanks for making this pull request.

there seems to be some merge conflicts. You can resolve them and request a review

**Review by orama254 — CHANGES_REQUESTED** [review]
kindly check on merge conflicts

**Comment by stephanieopala** [comment]
@achingachris On the Cheatsheets table, kindly update the Link title to Description since that column has descriptions.

**Comment by achingachris** [comment]
> @achingachris On the Cheatsheets table, kindly update the Link title to Description since that column has descriptions.

On it,thanks for pointing it out

**Comment by achingachris** [comment]
Screenshot from 2022-06-21 23-00-09
@stephanieopala Updated the Cheatsheet table

**Pull request merged**
